
###
GET http://localhost:3001/users
content-type: application/json

# {
#     "firstName": "test",
#     "lastName": "me",
#     "email": "aaaaaaa@gmail.com",
#     
#     "picturePath": "pic1.jpeg",
#     "friends": [],
#     "location": "San Fran, CA",
#     "occupation": "Software Engineer",
#     "viewedProfile": 14561,
#     "impressions": 100,    
# }

###